package entities;
// Generated 1 juil. 2019 11:22:54 by Hibernate Tools 5.4.2.Final

/**
 * AdministrateurId generated by hbm2java
 */
public class AdministrateurId implements java.io.Serializable {

	private int idpers;
	private int idadmin;

	public AdministrateurId() {
	}

	public AdministrateurId(int idpers, int idadmin) {
		this.idpers = idpers;
		this.idadmin = idadmin;
	}

	public int getIdpers() {
		return this.idpers;
	}

	public void setIdpers(int idpers) {
		this.idpers = idpers;
	}

	public int getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(int idadmin) {
		this.idadmin = idadmin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdministrateurId))
			return false;
		AdministrateurId castOther = (AdministrateurId) other;

		return (this.getIdpers() == castOther.getIdpers()) && (this.getIdadmin() == castOther.getIdadmin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpers();
		result = 37 * result + this.getIdadmin();
		return result;
	}

}
