package entities;
// Generated 1 juil. 2019 11:22:54 by Hibernate Tools 5.4.2.Final

/**
 * Administrateur generated by hbm2java
 */
public class Administrateur implements java.io.Serializable {

	private AdministrateurId id;
	private Personne personne;
	private Integer code;

	public Administrateur() {
	}

	public Administrateur(AdministrateurId id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public Administrateur(AdministrateurId id, Personne personne, Integer code) {
		this.id = id;
		this.personne = personne;
		this.code = code;
	}

	public AdministrateurId getId() {
		return this.id;
	}

	public void setId(AdministrateurId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

}
