package entities;
// Generated 1 juil. 2019 11:22:54 by Hibernate Tools 5.4.2.Final

/**
 * ClientId generated by hbm2java
 */
public class ClientId implements java.io.Serializable {

	private int idpers;
	private int idclient;

	public ClientId() {
	}

	public ClientId(int idpers, int idclient) {
		this.idpers = idpers;
		this.idclient = idclient;
	}

	public int getIdpers() {
		return this.idpers;
	}

	public void setIdpers(int idpers) {
		this.idpers = idpers;
	}

	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientId))
			return false;
		ClientId castOther = (ClientId) other;

		return (this.getIdpers() == castOther.getIdpers()) && (this.getIdclient() == castOther.getIdclient());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpers();
		result = 37 * result + this.getIdclient();
		return result;
	}

}
