package entities;
// Generated 1 juil. 2019 11:22:54 by Hibernate Tools 5.4.2.Final

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private ClientId id;
	private Personne personne;
	private Integer code;

	public Client() {
	}

	public Client(ClientId id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public Client(ClientId id, Personne personne, Integer code) {
		this.id = id;
		this.personne = personne;
		this.code = code;
	}

	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

}
