package entities;
// Generated 1 juil. 2019 11:22:54 by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Commercant generated by hbm2java
 */
public class Commercant implements java.io.Serializable {

	private CommercantId id;
	private Personne personne;
	private Integer code;
	private Set boutiques = new HashSet(0);

	public Commercant() {
	}

	public Commercant(CommercantId id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public Commercant(CommercantId id, Personne personne, Integer code, Set boutiques) {
		this.id = id;
		this.personne = personne;
		this.code = code;
		this.boutiques = boutiques;
	}

	public CommercantId getId() {
		return this.id;
	}

	public void setId(CommercantId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public Set getBoutiques() {
		return this.boutiques;
	}

	public void setBoutiques(Set boutiques) {
		this.boutiques = boutiques;
	}

}
