package entities;
// Generated 1 juil. 2019 11:22:54 by Hibernate Tools 5.4.2.Final

/**
 * CommercantId generated by hbm2java
 */
public class CommercantId implements java.io.Serializable {

	private int idpers;
	private int idcom;

	public CommercantId() {
	}

	public CommercantId(int idpers, int idcom) {
		this.idpers = idpers;
		this.idcom = idcom;
	}

	public int getIdpers() {
		return this.idpers;
	}

	public void setIdpers(int idpers) {
		this.idpers = idpers;
	}

	public int getIdcom() {
		return this.idcom;
	}

	public void setIdcom(int idcom) {
		this.idcom = idcom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommercantId))
			return false;
		CommercantId castOther = (CommercantId) other;

		return (this.getIdpers() == castOther.getIdpers()) && (this.getIdcom() == castOther.getIdcom());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpers();
		result = 37 * result + this.getIdcom();
		return result;
	}

}
