package entities;
// Generated 1 juil. 2019 11:22:54 by Hibernate Tools 5.4.2.Final

/**
 * Produit generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	private int idprod;
	private Integer codeproduit;
	private Integer nom;

	public Produit() {
	}

	public Produit(int idprod) {
		this.idprod = idprod;
	}

	public Produit(int idprod, Integer codeproduit, Integer nom) {
		this.idprod = idprod;
		this.codeproduit = codeproduit;
		this.nom = nom;
	}

	public int getIdprod() {
		return this.idprod;
	}

	public void setIdprod(int idprod) {
		this.idprod = idprod;
	}

	public Integer getCodeproduit() {
		return this.codeproduit;
	}

	public void setCodeproduit(Integer codeproduit) {
		this.codeproduit = codeproduit;
	}

	public Integer getNom() {
		return this.nom;
	}

	public void setNom(Integer nom) {
		this.nom = nom;
	}

}
